// Minimal OKF v0.2 helpers: walking, frontmatter parsing, link extraction, index rendering.
import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';

export const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..');
export const RESERVED = new Set(['index.md', 'log.md']);
const FM = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

/** Bundles are knowledge/ plus every deployments/<name>/ that has an index.md. */
export function findBundles() {
  const out = [];
  const core = path.join(ROOT, 'knowledge');
  if (fs.existsSync(core)) out.push(core);
  const dep = path.join(ROOT, 'deployments');
  if (fs.existsSync(dep)) {
    for (const d of fs.readdirSync(dep, { withFileTypes: true })) {
      const p = path.join(dep, d.name);
      if (d.isDirectory() && fs.existsSync(path.join(p, 'index.md'))) out.push(p);
    }
  }
  return out;
}

/** All directories (including root) and markdown files under a bundle, sorted. */
export function walk(bundle) {
  const dirs = [bundle];
  const files = [];
  const visit = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) {
        dirs.push(p);
        visit(p);
      } else if (e.name.endsWith('.md')) files.push(p);
    }
  };
  visit(bundle);
  return { dirs, files };
}

export function parseDoc(file) {
  const text = fs.readFileSync(file, 'utf8');
  const m = FM.exec(text);
  if (!m) return { fm: null, body: text, text };
  try {
    return { fm: YAML.parse(m[1]) ?? {}, body: text.slice(m[0].length), text };
  } catch (e) {
    return { fm: null, error: e.message, body: text, text };
  }
}

/** Markdown link targets outside fenced and inline code. */
export function extractLinks(body) {
  const clean = body.replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '');
  const re = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
  const out = [];
  let m;
  while ((m = re.exec(clean))) out.push(m[1]);
  return out;
}

export const isExternal = (t) => /^[a-z][a-z0-9+.-]*:/i.test(t) || t.startsWith('#');

/** Resolve a link to an absolute filesystem path. `/x` is bundle-relative. */
export function resolveLink(target, fromFile, bundle) {
  const clean = target.split('#')[0].split('?')[0];
  if (!clean) return null;
  return clean.startsWith('/') ? path.join(bundle, clean) : path.resolve(path.dirname(fromFile), clean);
}

export const rel = (p) => path.relative(ROOT, p);
const titleOf = (file, fm) => fm?.title ?? path.basename(file, '.md');

/** Deterministic index.md content for one directory of a bundle. */
export function renderIndex(dir, bundle) {
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  const concepts = [];
  const subdirs = [];
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      const has = walk(p).files.some((f) => !RESERVED.has(path.basename(f)));
      if (has) subdirs.push(e.name);
    } else if (e.name.endsWith('.md') && !RESERVED.has(e.name)) {
      const { fm } = parseDoc(p);
      concepts.push({ name: e.name, title: titleOf(p, fm), desc: fm?.description ?? '' });
    }
  }
  const isRoot = dir === bundle;
  let out = '';
  if (isRoot) {
    const existing = fs.existsSync(path.join(dir, 'index.md')) ? parseDoc(path.join(dir, 'index.md')).fm : null;
    out += `---\nokf_version: "${existing?.okf_version ?? '0.2'}"\n---\n\n`;
  }
  const heading = path.basename(dir).replace(/[-_]/g, ' ');
  out += `<!-- Generated by scripts/okf-index.mjs. Do not edit by hand. -->\n\n`;
  if (concepts.length) {
    out += `# ${isRoot ? 'Concepts' : heading[0].toUpperCase() + heading.slice(1)}\n\n`;
    for (const c of concepts) out += `* [${c.title}](${c.name})${c.desc ? ` - ${c.desc}` : ''}\n`;
    out += '\n';
  }
  if (subdirs.length) {
    out += `# Sections\n\n`;
    for (const s of subdirs) out += `* [${s}](${s}/)\n`;
    out += '\n';
  }
  return out.trimEnd() + '\n';
}
